name: Deploy Rust Auth API

on:
  push:
    branches:
      - main

jobs:
  build-and-restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build backend
        run: cargo build --release

      - name: Deploy to server and restart service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /path/to/your/app
            git pull origin main
            cargo build --release
            # Restart your service (adjust the command as needed)
            systemctl --user restart auth_api.service